#!/usr/bin/env bash

# Books directory
BOOKS_DIR="/tank/dropbox/ebooks /tank/dropbox/articles /tank/dropbox/armclass/docs"

# Save find result to F_ARRAY
readarray -t F_ARRAY <<< "$(find $BOOKS_DIR -type f -name '*.pdf')"

# Associative array for storing books
# key => book name
# value => absolute path to the file
# BOOKS['filename']='path'
declare -A BOOKS

# Add elements to BOOKS array
get_books() {
    for i in "${!F_ARRAY[@]}"
    do
        path=${F_ARRAY[$i]}
        file=$(basename "${F_ARRAY[$i]}")
        BOOKS+=(["$file"]="$path")
    done
}

# List for rofi
gen_list(){
    for i in "${!BOOKS[@]}"
    do
        echo "$i"
    done
}

get_books
gen_list

if [ ! -z "$@" ]
then
    coproc (exo-open "${BOOKS[$@]}" > /dev/null 2>&1 )
    #exec 1>&-
    exit;
fi
